
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftNOTAND FALSE LITERAL LPAREN NOT OR RPAREN TRUEformula : LITERALformula : formula AND formulaformula : formula OR formulaformula : NOT formulaformula : LPAREN formula RPARENformula : TRUEformula : FALSE'
    
_lr_action_items = {'LITERAL':([0,3,4,7,8,],[2,2,2,2,2,]),'NOT':([0,3,4,7,8,],[3,3,3,3,3,]),'LPAREN':([0,3,4,7,8,],[4,4,4,4,4,]),'TRUE':([0,3,4,7,8,],[5,5,5,5,5,]),'FALSE':([0,3,4,7,8,],[6,6,6,6,6,]),'$end':([1,2,5,6,9,11,12,13,],[0,-1,-6,-7,-4,-2,-3,-5,]),'AND':([1,2,5,6,9,10,11,12,13,],[7,-1,-6,-7,-4,7,-2,7,-5,]),'OR':([1,2,5,6,9,10,11,12,13,],[8,-1,-6,-7,-4,8,-2,-3,-5,]),'RPAREN':([2,5,6,9,10,11,12,13,],[-1,-6,-7,-4,13,-2,-3,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,3,4,7,8,],[1,9,10,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> LITERAL','formula',1,'p_formula_literal','logic_parser.py',72),
  ('formula -> formula AND formula','formula',3,'p_formula_and','logic_parser.py',76),
  ('formula -> formula OR formula','formula',3,'p_formula_or','logic_parser.py',80),
  ('formula -> NOT formula','formula',2,'p_formula_not','logic_parser.py',84),
  ('formula -> LPAREN formula RPAREN','formula',3,'p_formula_formula_par','logic_parser.py',88),
  ('formula -> TRUE','formula',1,'p_formula_true','logic_parser.py',92),
  ('formula -> FALSE','formula',1,'p_formula_false','logic_parser.py',96),
]
