
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftMINUSleftPLUSleftDIVleftTIMESDIV LITERAL LPAREN MINUS NUM PLUS RPAREN TIMESformula : expformula : MINUS formulaformula : formula TIMES formulaformula : formula PLUS formulaformula : formula MINUS formulaformula : formula DIV formulaformula : LPAREN formula RPARENexp : NUMexp : LITERAL'
    
_lr_action_items = {'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[3,9,-1,3,3,-8,-9,3,3,3,3,-2,9,-3,-4,-5,-6,-7,]),'LPAREN':([0,3,4,7,8,9,10,],[4,4,4,4,4,4,4,]),'NUM':([0,3,4,7,8,9,10,],[5,5,5,5,5,5,5,]),'LITERAL':([0,3,4,7,8,9,10,],[6,6,6,6,6,6,6,]),'$end':([1,2,5,6,11,13,14,15,16,17,],[0,-1,-8,-9,-2,-3,-4,-5,-6,-7,]),'TIMES':([1,2,5,6,11,12,13,14,15,16,17,],[7,-1,-8,-9,7,7,-3,7,7,7,-7,]),'PLUS':([1,2,5,6,11,12,13,14,15,16,17,],[8,-1,-8,-9,8,8,-3,-4,8,-6,-7,]),'DIV':([1,2,5,6,11,12,13,14,15,16,17,],[10,-1,-8,-9,10,10,-3,10,10,-6,-7,]),'RPAREN':([2,5,6,11,12,13,14,15,16,17,],[-1,-8,-9,-2,17,-3,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'formula':([0,3,4,7,8,9,10,],[1,11,12,13,14,15,16,]),'exp':([0,3,4,7,8,9,10,],[2,2,2,2,2,2,2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> exp','formula',1,'p_formula_exp','calculator.py',74),
  ('formula -> MINUS formula','formula',2,'p_formula_negative','calculator.py',78),
  ('formula -> formula TIMES formula','formula',3,'p_formula_formula_times_formula','calculator.py',82),
  ('formula -> formula PLUS formula','formula',3,'p_formula_formula_plus_formula','calculator.py',86),
  ('formula -> formula MINUS formula','formula',3,'p_formula_formula_minus_formula','calculator.py',90),
  ('formula -> formula DIV formula','formula',3,'p_formula_formula_div_formula','calculator.py',94),
  ('formula -> LPAREN formula RPAREN','formula',3,'p_formula_paren_formula','calculator.py',98),
  ('exp -> NUM','exp',1,'p_exp_num','calculator.py',102),
  ('exp -> LITERAL','exp',1,'p_exp_lit','calculator.py',106),
]
